language: java
sudo: required
cache:
  - .m2/repository
env:
  - M2_HOME=$(pwd)/.m2
install:
  - true
before_deploy:
  - pwd
  - mvn clean
  - mvn dependency:go-offline
  - mvn test
  - mvn package -DskipTests
  - tar -zcvf /tmp/amazon-kinesis-agent-${TRAVIS_TAG}.tgz .
deploy:
  - provider: releases
    file: /tmp/amazon-kinesis-agent-${TRAVIS_TAG}.tgz
    api_key: "$OAUTH_TOKEN"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
